before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: mi3DJdcfn62LO3mMN0yc9FjVfrtwRe+0wc2IV6tKBYnJFmfo3dLVR/s+rkJon8xk7q2VL9N9HfxsvvWeOxso+cLV8HleVkM/jFQ7JklOdMc1Bed+j2vrUqeFWPPFSMEnwivn+kYc0/xsXPQJKgGA9zKXGly/xK5i0NpWM2O2ezVYGKr2aiZjKHqZ/rRWJAeEHfP0yfiAxVsfLL1UHroMQE8AdHw4t7sBgslxadKFsvJF9LyuZkjPT1NKo2m0m1RYxv8UdZnoC5AjzRJkDn4K6zRzdTHV3dS0XWMZW3tFaEyXYfNS0lYOxRWwI58hHJn3hRG/h+XAJ3/QYytcuRveTk1I7jikxRJQA1kw4o2+t7vddf+CuOKyPEJZ81uWR12lvGvd5UaKfSUCF4zQ/9zdM1iRL0rGVrfOD8xsOlA5XFdVLQ8GHSGncOpmAGRjm3dKs+546NXJsy7asod3zFmLK963Kurw0KOOqbJeUTtkzSX+ASA68LpHvr4ieF0aJhrLuvp635CCWbFEBBKy8zGn2DlmIfLS8VA3BLN2Y9xmd3sqhi2vplwb2dVfPQvC8FnbgfdGaxehek6j2M9tOOVcYD9yI8vgLGUn4TENSTN2iR8QFPWpU8Un5kk2nrLgsuYpJnh53wnvqz8nWKtJdDAcHUzmZQAtfz4g8z2pu8UCTKY= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
